### ISSUE TITLE
Cannot connect to Google Cloud Services

### ISSUE THREAD

**Issue by jacobarriola** [EmberMeetup/website#27]
Hello,

I'm trying to help resolve issue #26 but am running into issues when trying to run `ember serve` locally. Specifically, the ember server fails to run and the following message is echoed in the Terminal:

```bash
Sorry, we cannot connect to Google Cloud Services without a project ID. You may specify one with an environment variable named "GCLOUD_PROJECT". See https://googlecloudplatform.github.io/gcloud-node/#/authentication for a detailed guide on creating an authenticated connection.
Error: Sorry, we cannot connect to Google Cloud Services without a project ID. You may specify one with an environment variable named "GCLOUD_PROJECT". See https://googlecloudplatform.github.io/gcloud-node/#/authentication for a detailed guide on creating an authenticated connection.
    at Object.<anonymous> (/Users/amorcito/Documents/Websites/embermeetup/node_modules/ember-cli-deploy-gcloud/node_modules/gcloud/lib/common/util.js:47:29)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/amorcito/Documents/Websites/embermeetup/node_modules/ember-cli-deploy-gcloud/node_modules/gcloud/lib/common/service-object.js:31:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

Is there some step that I'm missing? Thanks!

Repro steps:

1. Fork repo
2. Clone forked repo onto local environment
3. `npm install` 
4. `bower install`
5. `ember serve`

**Comment by jorgelainfiesta** [comment]
Hi, I just checked and it's indeed broken. We have to check this with one of the Google Cloud addons used by the project. As a temporary solution, you could do something like:

```
GCLOUD_PROJECT=foo ember server
```

**Comment by taras** [comment]
@jorgelainfiesta I published ember-cli-deploy-gcloud 0.2.2 which should fix this problem. Can you please update it?

**Comment by jorgelainfiesta** [comment]
PR sent: #28

**Comment by jacobarriola** [comment]
Where should I include that declaration?

**Comment by jorgelainfiesta** [comment]
@jacobarriola please try to pull the latest master and check if the error is still happening

**Comment by jacobarriola** [comment]
Sorry about that, @jorgelainfiesta. Somehow my comment post was really delayed. 🤔

I'll merge in the latest and will retry tonight. Saludos!

**Comment by jorgelainfiesta** [comment]
Oh that's weird. Thanks!

**Comment by jacobarriola** [comment]
All set! Thanks.
